/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.markwalder.junit.mailserver;

import org.junit.jupiter.api.Test;

class SmtpServerTest {

	@Test
	void test() {

	}
}
